apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-instalacao-lab
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: nginx-instalacao
    title: "Instalação e Configuração Básica do NGINX"
    description: "Aprenda a instalar, configurar e gerenciar o servidor web NGINX em um ambiente Linux. Este laboratório guiado apresenta os passos essenciais para configurar um servidor web básico, entender os arquivos de configuração e realizar operações comuns de administração."
    duration: 20m
    image: "linuxtips/girus-devops:0.1"
    tasks:
      - name: "Instalação do NGINX"
        description: "Aprenda a instalar o servidor NGINX em um sistema Linux baseado em Debian/Ubuntu."
        steps:
          - "**Atualizando o Sistema**"
          - "Antes de instalar qualquer pacote, é recomendável atualizar a lista de repositórios do sistema:"
          - "`sudo apt update`"
          - "**Instalando o NGINX**"
          - "Para instalar o NGINX, execute o seguinte comando:"
          - "`sudo apt install nginx -y`"
          - "O parâmetro '-y' responde automaticamente 'sim' para todas as perguntas durante a instalação."
          - "**Verificando a Instalação**"
          - "Após a instalação, verifique se o NGINX está funcionando corretamente:"
          - "`sudo systemctl status nginx`"
          - "Você deve ver 'active (running)' no status do serviço."
          - "**Acesso via Navegador**"
          - "Em um ambiente de desktop ou se você tiver acesso ao navegador, acesse http://localhost para ver a página padrão do NGINX."
          - "Alternativamente, você pode verificar usando curl:"
          - "`curl http://localhost`"
          - "Isto exibirá o HTML da página padrão do NGINX."
        tips:
          - type: "info"
            title: "Inicialização Automática"
            content: "Por padrão, o NGINX é configurado para iniciar automaticamente quando o sistema é reiniciado."
          - type: "tip"
            title: "Firewall"
            content: "Se você estiver usando um firewall como o UFW, talvez precise permitir o tráfego HTTP com o comando: 'sudo ufw allow 'Nginx HTTP''."
        validation:
          - command: "command -v nginx && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "NGINX não está instalado corretamente."
          - command: "systemctl is-active nginx && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "O serviço NGINX não está ativo."

      - name: "Entendendo a Estrutura de Arquivos do NGINX"
        description: "Explore a estrutura de diretórios e arquivos de configuração do NGINX para entender seu funcionamento."
        steps:
          - "**Diretórios Principais**"
          - "O NGINX utiliza vários diretórios importantes:"
          - "`ls -la /etc/nginx`"
          - "Os principais diretórios e arquivos incluem:"
          - "- `/etc/nginx/`: Diretório de configuração principal"
          - "- `/etc/nginx/nginx.conf`: Arquivo de configuração global"
          - "- `/etc/nginx/sites-available/`: Configurações de sites disponíveis"
          - "- `/etc/nginx/sites-enabled/`: Sites ativos (normalmente links simbólicos para sites-available)"
          - "- `/var/log/nginx/`: Logs de acesso e erro"
          - "- `/var/www/html/`: Diretório padrão para arquivos servidos pelo NGINX"
          - "**Explorando o Arquivo de Configuração Principal**"
          - "Vamos examinar o arquivo de configuração principal:"
          - "`cat /etc/nginx/nginx.conf`"
          - "Este arquivo contém configurações globais do NGINX, incluindo:"
          - "- Contexto 'http' para configurações gerais de HTTP"
          - "- Inclusão automática de arquivos em sites-enabled"
          - "- Configurações de worker_processes para desempenho"
          - "- Configurações de log"
          - "**Configuração do Site Padrão**"
          - "Examine a configuração do site padrão:"
          - "`cat /etc/nginx/sites-available/default`"
          - "Este arquivo define como o site padrão do NGINX responde às requisições."
          - "Os principais elementos incluem:"
          - "- Bloco 'server' que define um servidor virtual"
          - "- Diretiva 'listen' que especifica porta e protocolo"
          - "- Diretiva 'root' que define o diretório raiz dos arquivos"
          - "- Blocos 'location' que definem como lidar com diferentes URIs"
          - "**Conteúdo do Site**"
          - "Verifique o conteúdo do diretório raiz do site padrão:"
          - "`ls -la /var/www/html`"
          - "O arquivo index.html neste diretório é a página padrão que você vê ao acessar o servidor NGINX."
        tips:
          - type: "warning"
            title: "Alterações de Configuração"
            content: "Sempre verifique a sintaxe das configurações antes de recarregar o NGINX com: 'sudo nginx -t'."
          - type: "info"
            title: "Links Simbólicos"
            content: "O NGINX usa links simbólicos em sites-enabled para ativar sites definidos em sites-available, permitindo fácil ativação/desativação de sites."
        validation:
          - command: "test -d /etc/nginx && test -f /etc/nginx/nginx.conf && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "Os arquivos de configuração do NGINX não foram encontrados."
          - command: "test -d /var/www/html && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "O diretório raiz padrão do NGINX não foi encontrado."

      - name: "Configuração Básica e Gerenciamento do NGINX"
        description: "Aprenda a realizar configurações básicas, criar sites simples e gerenciar o serviço NGINX."
        steps:
          - "**Criando uma Página Web Personalizada**"
          - "Vamos criar uma página HTML simples para substituir a página padrão:"
          - "`sudo bash -c 'cat > /var/www/html/index.html << EOF"
          - "<html>"
          - "<head>"
          - "    <title>Meu Site NGINX</title>"
          - "</head>"
          - "<body>"
          - "    <h1>Bem-vindo ao meu servidor NGINX!</h1>"
          - "    <p>Esta página foi criada como parte do laboratório de instalação do NGINX no Girus.</p>"
          - "    <p>Data de criação: $(date)</p>"
          - "</body>"
          - "</html>"
          - "EOF'`"
          - "**Verificando a Nova Página**"
          - "Verifique se a nova página está acessível:"
          - "`curl http://localhost`"
          - "Você deve ver o conteúdo HTML que acabamos de criar."
          - "**Gerenciando o Serviço NGINX**"
          - "O NGINX pode ser controlado através do systemd como qualquer outro serviço:"
          - "Para parar o serviço:"
          - "`sudo systemctl stop nginx`"
          - "Para iniciar o serviço:"
          - "`sudo systemctl start nginx`"
          - "Para reiniciar o serviço:"
          - "`sudo systemctl restart nginx`"
          - "Para recarregar a configuração sem interromper o serviço:"
          - "`sudo systemctl reload nginx`"
          - "**Configurando um Host Virtual Básico**"
          - "Os hosts virtuais permitem servir múltiplos sites a partir do mesmo servidor:"
          - "`sudo bash -c 'cat > /etc/nginx/sites-available/meusite << EOF"
          - "server {"
          - "    listen 8080;"
          - "    server_name localhost;"
          - "    root /var/www/meusite;"
          - "    index index.html;"
          - "    location / {"
          - "        try_files \\$uri \\$uri/ =404;"
          - "    }"
          - "}"
          - "EOF'`"
          - "**Criando o Diretório e Conteúdo do Novo Site**"
          - "Crie o diretório para o novo site:"
          - "`sudo mkdir -p /var/www/meusite`"
          - "Crie uma página HTML para o novo site:"
          - "`sudo bash -c 'cat > /var/www/meusite/index.html << EOF"
          - "<html>"
          - "<head>"
          - "    <title>Meu Site Personalizado</title>"
          - "</head>"
          - "<body>"
          - "    <h1>Meu Site na Porta 8080</h1>"
          - "    <p>Este é um exemplo de host virtual NGINX configurado na porta 8080.</p>"
          - "</body>"
          - "</html>"
          - "EOF'`"
          - "**Ativando o Novo Site**"
          - "Crie um link simbólico para ativar o novo site:"
          - "`sudo ln -s /etc/nginx/sites-available/meusite /etc/nginx/sites-enabled/`"
          - "Verifique a configuração:"
          - "`sudo nginx -t`"
          - "Se não houver erros, recarregue o NGINX:"
          - "`sudo systemctl reload nginx`"
          - "**Acessando o Novo Site**"
          - "Teste o acesso ao novo site na porta 8080:"
          - "`curl http://localhost:8080`"
        tips:
          - type: "tip"
            title: "Hosts Virtuais Baseados em Nome"
            content: "Para criar hosts virtuais baseados em nome de domínio, você usaria a diretiva 'server_name' com o nome de domínio desejado e configuraria o DNS adequadamente."
          - type: "info"
            title: "Logs"
            content: "Sempre verifique os logs em /var/log/nginx/ para diagnosticar problemas. Os principais são 'error.log' e 'access.log'."
          - type: "warning"
            title: "Permissões"
            content: "Certifique-se de que o usuário 'www-data' (usado pelo NGINX) tem permissões adequadas para acessar os arquivos do seu site."
        validation:
          - command: "curl -s http://localhost | grep -q 'Bem-vindo ao meu servidor NGINX' && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "A página personalizada não está funcionando corretamente na porta 80."
          - command: "curl -s http://localhost:8080 | grep -q 'Meu Site na Porta 8080' && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "O host virtual na porta 8080 não está funcionando corretamente."