apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-fundamentos2-lab
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: terraform-aws-infraestrutura2
    title: "Terraform com AWS: Construindo Infraestrutura em Nuvem 2"
    description: "Aprenda a usar o Terraform para provisionar e gerenciar recursos na AWS, criando uma infraestrutura completa com recursos como VPC, EC2, RDS e S3."
    duration: 30m
    timerEnabled: true
    maxDuration: 30m
    image: "linuxtips/girus-localstack:0.1"
    privileged: true
    type: "aws"
    entrypoint: "/entrypoint.sh"
    tasks:
      - name: "Instalando o Vim"
        description: "Atualize os repositórios do sistema e instale o editor Vim"
        steps:
          - "Atualize os repositórios do sistema:"
          - "`apt update`"
          - "Instale o editor Vim:"
          - "`apt install -y vim`"
          - "Verifique se o Vim foi instalado corretamente:"
          - "`vim --version | head -n 1`"
        tips:
          - type: "info"
            title: "Comandos básicos do Vim"
            content: "Para abrir um arquivo use 'vim arquivo.tf'. Para inserir texto, pressione 'i'. Para salvar e sair, pressione 'ESC' e digite ':wq'. Para sair sem salvar, pressione 'ESC' e digite ':q!'."
        validation:
          - command: "which vim > /dev/null && echo 'success' || echo 'error'"
            expectedOutput: "success"
            errorMessage: "O Vim não foi instalado corretamente. Tente executar 'apt install -y vim' novamente."

